version: '3.8'
services:
    redis:
        image: 'redis:alpine'

    mysql:
        image: 'mysql:8.0'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=app
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            - '16002:3306'

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '16000:80'

    php-fpm:
        build: .
        working_dir: /app
        volumes:
            - '.:/app'
            - './php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'